apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postbot

resources:
  - namespace.yaml
  - configmap.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml

# Images will be set by overlays (local or production)
